### ISSUE TITLE
有没有办法 重新 构建一些低语言版本的？

### ISSUE THREAD

**Issue by zero16832** [axojhf/MDK.SDK.NET#1]
有没有办法 重新 构建一些低语言版本的？ 比如 8之类的？你是采用cppsharp 还是 clangsharp的丫？

**Comment by axojhf** [comment]
> 有没有办法 重新 构建一些低语言版本的？ 比如 8之类的？你是采用cppsharp 还是 clangsharp的丫？

ClangSharp，不过我把DllImport改成了LibraryImport

其他的c#12语法我不太记得了，你可以试试编译调试看看

我记得好像是c# 9才有函数指针的，如果改到c#8，可能代码得大改

**Comment by axojhf** [comment]
如果目的是想在.net framework上用，可以试试调整target到合适的.net standard版本上，未必一定要把c#版本降到太低

**Comment by zero16832** [comment]
我想在将这玩意 用在 Unity 上面 ，Unity 对 c#的支持 有限
