### ISSUE TITLE
如何取出帧数据？

### ISSUE THREAD

**Issue by zero16832** [axojhf/MDK.SDK.NET#2]
我根据你的代码 仿写了如下：
        _player = new MDKPlayer();

        _player.SetDecoders(MediaType.Video,
            new List<string> { "MFT:d3d=11", "hap", "D3D11", "DXVA", "CUDA", "FFmpeg", "dav1d" });
        _player.SetAudioBackends(new List<string> { "OpenAL", "XAudio2" });
        _player.SetMedia(url);
        _player.Set(State.Playing);
        _player.OnEvent(e =>
        {
            Debug.Log("event: " + e.Category + ", detail: " + e.Detail);
            return false;
        });

        _player.Set(State.Playing);
        _player.OnFrame((frame, track) =>
        {
            var data = frame.BufferData();
            var width = frame.Width();
            var height = frame.Height();
            var size = width * height * 3;
            var frameData = new byte[size];

            Marshal.Copy(frameData, 0, data, size);

            RunInUnityMainThread(() =>
            {
                if (width > 0 && height > 0)
                {
                    if (videoTex == null)
                    {
                        videoTex = new Texture2D(width, height, TextureFormat.RGB24, false);
                        videoImage.texture = videoTex;
                    }

                    videoTex.LoadRawTextureData(frameData);
                    videoTex.Apply();
                }
            });

            return 0;
        });

但是 并没有得到正常的图像数据，我还缺点啥？

**Comment by axojhf** [comment]
Frame相关的东西我还没用过，单纯做了个初级的绑定，当初也没管跑不跑的通，~~有bug就对了~~
建议先打几个断点看看😂，有空我再测试
不知道原项目有没有操作帧数据的例子

**Comment by axojhf** [comment]
看了一下，大概要先把VideoFrame按照一个指定的PixelFormat转换，然后用BufferData这个方法大概就不会报错了
比如：
```csharp
var newFrame = frame.To(PixelFormat.BGRA);
var data = newFrame.BufferData();
```
我在这里把VideoFrame.To暴露出来了，你对照着看看
https://github.com/axojhf/MDK.SDK.NET/commit/f3bec148faf9ddcfc490998a919ff5f0c595ff8f

**Comment by axojhf** [comment]
还有啥问题么，没啥问题我就关Issue了
